version: '3.8'
services:
  redis_cache:
    container_name: c_redis2
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
        # command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local